refresh token improvements
fs/react-next-base pull request #102
Opened 2021-02-09 13:08 UTC by Nikita-Polyakov

2021-02-10 09:15 UTC, RenasSitdikov requested changes
Creates new bugs

2021-02-10 10:42 UTC, RenasSitdikov approved these changes

2021-02-11 06:05 UTC, nadezhdakharchuk commented on cypress.env.json
> +{
Could you please remove this file

2021-02-11 06:07 UTC, nadezhdakharchuk commented on lib/auth/tokens.js
> +  if (req && req.secure) attributes.push('Secure');
Can we use here optional chaining operator?
`req?.secure`

2021-02-26 14:33 UTC, merged